### ISSUE TITLE
--exclude option with regex path

### ISSUE THREAD

**Issue by hroncok** [frenzymadness/compileall2#5]
brp-python-bytecompile has exclude option with path regex:

https://github.com/rpm-software-management/rpm/blob/master/scripts/brp-python-bytecompile

It uses this regex not to compile stuff in some dirs:

    "/bin/|/sbin/|/usr/lib(64)?/python[0-9]\.[0-9]|/usr/share/doc"

In order to be able to use compileall2 in brp-python-bytecompile, it needs to gain support for exclude option. It can either support regular expressions or repeated file globs.

I suppose for us it will be more convenient to check the excluded paths after the `-s` and `-a` options are applied.

**Comment by frenzymadness** [comment]
There already is `-x` option for regex exclude https://github.com/frenzymadness/compileall2/blob/master/compileall2.py#L341

Do you mean something different?

**Comment by hroncok** [comment]
Ah! Sorry.

**Comment by frenzymadness** [comment]
Moreover, `-x` regex search is applied on original `.py` file path, not on path compiled into `.pyc` file so it can be evaulated either before or after `-s`/`-a` options.

**Comment by hroncok** [comment]
> can be evaulated either before or after -s/-a options.

Huh? Got examples?

**Comment by frenzymadness** [comment]
When compilling a file, you have two paths:

- one which is compiled into `pyc` file (let's call it dfile)
- and one which is a path to the actual `py` file (let's call it fullname)

these two paths are usually the same

`-a`/`-s` options are applied to dfile but `-x` can skip a file compilation based on fullname no matter how dfile was changed

**Comment by hroncok** [comment]
Nice!
```
$ ls empty/
zero.py
$ python3.7 -m compileall2 -o 0 -o 1 -a /usr empty/ -x /usr/empty
Listing 'empty/'...
$ ls empty/
zero.py
```
